apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: good-app
  template:
    metadata:
      labels:
        app: good-app
    spec:
      containers:
        - name: good
          image: nginx:1.25
          ports:
            - containerPort: 8080
